name: Main Build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  npm-merge:
    uses: devopsplaybook-io/common-utils/.github/workflows/reusable-npm-merge.yml@main
    with:
      npm_package_name: "@devopsplaybook.io/otel-utils-fastify"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
