name: PR Check

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  npm-pr:
    uses: devopsplaybook-io/common-utils/.github/workflows/reusable-npm-pr.yml@main
    with:
      npm_package_name: "@devopsplaybook.io/otel-utils-fastify"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
